language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "taishiwo1995" | docker login -u "linjintai" --password-stdin
  - docker build -t linjintai/docker_web_deploy:latest .
  - docker push linjintai/docker_web_deploy:latest